package com.github.INIT_SGGW.MonoTanksClient.websocket;

public enum Warning {
    PLAYER_ALREADY_MADE_ACTION_WARNING,
    MISSING_GAME_STATE_ID_WARNING,
    SLOW_RESPONSE_WARNING,
    ACTION_IGNORED_DUE_TO_DEAD_WARNING,
    CUSTOM_WARNING;
}
